In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [4]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

## Logistic Regression

In [6]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9592592592592593

## SVM

In [7]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9925925925925926

## Random Forest Classifier

In [8]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

## KFold Cross Validation

In [9]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

### Logistic Regression

In [12]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

0.9592592592592593

### SVC

In [13]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9925925925925926

### Random Forest Classifier

In [14]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9611111111111111

# StratifiedKFold

In [17]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)

In [24]:
score_lr = []
score_svm = []
score_rf = []
for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    score_lr.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [25]:
score_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [26]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [27]:
score_rf

[0.9348914858096828, 0.9432387312186978, 0.9232053422370617]

# Cross Validation Score

In [28]:
from sklearn.model_selection import cross_val_score

In [29]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [30]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [31]:
cross_val_score(RandomForestClassifier(n_estimators=540), digits.data, digits.target)

array([0.93611111, 0.91666667, 0.95543175, 0.96935933, 0.93314763])

### Hyperparameter Tuning

In [32]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)

array([0.84166667, 0.77222222, 0.88857939, 0.9275766 , 0.83286908])

In [33]:
cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target)

array([0.93055556, 0.90555556, 0.95264624, 0.95543175, 0.9275766 ])