In [17]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings('ignore')

from sklearn.datasets import load_iris

iris = load_iris()

In [18]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [19]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [20]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [21]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [22]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [23]:
iris.data.shape

(150, 4)

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

# Logistic Regression

In [25]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9555555555555556

# SVM

In [26]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9777777777777777

# Random Forest Classifier

In [27]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9555555555555556

# KFold Cross Validation

In [29]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [30]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# Generate Score through function

In [31]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

### Logistic Regression Score thourgh Function

In [33]:
get_score(LogisticRegression(), X_train, X_test, y_train,y_test)

0.9555555555555556

### SVM Score thourgh Function

In [34]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9777777777777777

### Random Forest Classifier Score thourgh Function

In [35]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9555555555555556

# StratifiedKFold

In [36]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)
fold

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [39]:
for train_index, test_index in fold.split(iris.data, iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], iris.target[train_index], iris.target[test_index]

    print(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    print(get_score(SVC(), X_train, X_test, y_train, y_test))
    print(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

0.98
0.96
0.98
0.96
0.98
0.94
0.98
0.94
0.96


In [40]:
score_lr = []
score_svm = []
score_rf = []
for train_index, test_index in fold.split(iris.data, iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], iris.target[train_index], iris.target[test_index]

    score_lr.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [41]:
score_lr

[0.98, 0.96, 0.98]

In [42]:
score_svm

[0.96, 0.98, 0.94]

In [43]:
score_rf

[0.98, 0.94, 0.92]

In [45]:
acc_lr = 0
count = 0
for i in score_lr:
    acc_lr += i
    count += 1
accuracy_lr = acc_lr / count
print(accuracy_lr)

0.9733333333333333


In [47]:
acc_svm = 0
count = 0
for i in score_svm:
    acc_svm += i
    count += 1
accuracy_svm = acc_svm / count
print(accuracy_svm)

0.96


In [50]:
acc_rf = 0
count = 0
for i in score_rf:
    acc_rf += i
    count += 1
accuracy_rf = acc_rf / count
print(accuracy_rf)

0.9466666666666667


# Cross Validation Score

In [51]:
from sklearn.model_selection import cross_val_score

In [53]:
cross_val_score(LogisticRegression(), iris.data, iris.target)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [54]:
cross_val_score(SVC(), iris.data, iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [55]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

### Hyperparameter Tuning

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)