In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('C:/Users/hp/OneDrive/Documents/Machine Learning Practice/Datasets/2_linear_reg_multivariate/Exercise/hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df['experience'] = df['experience'].fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [5]:
from word2number import w2n
df['experience'] = df['experience'].apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [12]:
import math
mean_val = math.floor(df['test_score(out of 10)'].mean())
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mean_val)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0               8.000000                           9      50000
1           0               8.000000                           6      45000
2           5               6.000000                           7      60000
3           2              10.000000                          10      65000
4           7               9.000000                           6      70000
5           3               7.000000                          10      62000
6          10               7.857143                           7      72000
7          11               7.000000                           8      80000

In [13]:
model = LinearRegression()
model.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [14]:
model.coef_

array([2827.63404314, 1912.93803053, 2196.9753141 ])

In [15]:
model.intercept_

17237.330313727216

In [22]:
model.predict([[2, 9, 6]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53290.89255945])

In [23]:
model.coef_[0] * 2 + model.coef_[1] * 9 + model.coef_[2] * 6 + model.intercept_

53290.892559447646

In [24]:
model.predict([[12, 10, 10]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92268.07227784])

In [26]:
model.coef_[0] * 12 + model.coef_[1] * 10 + model.coef_[2] * 10 + model.intercept_

92268.07227783564

In [32]:
pred = model.predict(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']])
pred

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [33]:
df['pred'] = pred
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0           0               8.000000                           9      50000   
1           0               8.000000                           6      45000   
2           5               6.000000                           7      60000   
3           2              10.000000                          10      65000   
4           7               9.000000                           6      70000   
5           3               7.000000                          10      62000   
6          10               7.857143                           7      72000   
7          11               7.000000                           8      80000   

           pred  
0  52313.612385  
1  45722.686443  
2  58231.955911  
3  63991.731846  
4  67429.062775  
5  61080.551798  
6  75922.725327  
7  79307.673515

In [35]:
residual = df['salary($)'] - df['pred']
residual

0   -2313.612385
1    -722.686443
2    1768.044089
3    1008.268154
4    2570.937225
5     919.448202
6   -3922.725327
7     692.326485
dtype: float64

In [37]:
df['residual'] = residual
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0           0               8.000000                           9      50000   
1           0               8.000000                           6      45000   
2           5               6.000000                           7      60000   
3           2              10.000000                          10      65000   
4           7               9.000000                           6      70000   
5           3               7.000000                          10      62000   
6          10               7.857143                           7      72000   
7          11               7.000000                           8      80000   

           pred     residual  
0  52313.612385 -2313.612385  
1  45722.686443  -722.686443  
2  58231.955911  1768.044089  
3  63991.731846  1008.268154  
4  67429.062775  2570.937225  
5  61080.551798   919.448202  
6  75922.725327 -3922.725327  
7  79307.673515   692.326485

In [38]:
#Residual Sum Squared
rss = np.sum(df['residual'] ** 2)
rss

33339855.691710517

In [39]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [41]:
mse = mean_squared_error(df['salary($)'], df['pred'])
mse

4167481.9614638146

In [42]:
mae = mean_absolute_error(df['salary($)'], df['pred'])
mae

1739.7560385573852

In [43]:
import math
rmse = math.sqrt(mse)
rmse

2041.4411481754291

In [ ]:
accuracy = accuracy_score(df['salary($)', df[')
print(f'Accuracy: {accuracy}')