In [4]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [5]:
df = pd.read_csv('Datasets/homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df['price'])

LinearRegression()

In [7]:
model.coef_

array([135.78767123])

In [8]:
model.intercept_

180616.43835616432

In [9]:
model.predict([[5000]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

Save the model using Pickle

In [10]:
import pickle
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [11]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [12]:
mp.predict([[5000]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [13]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [14]:
import joblib

In [15]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [16]:
mj = joblib.load('model_joblib')
mj.predict([[5000]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])